sudo: required
services:
  - docker

before_install:
  - docker build -t ktoni/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ktoni/react-test npm test

after_success:
  - docker build -t ktoni/multi-client ./client
  - docker build -t ktoni/multi-nginx ./nginx
  - docker build -t ktoni/multi-server ./server
  - docker build -t ktoni/multi-worker ./worker
  #LOGIN to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push it to docker hub
  - docker push ktoni/multi-client
  - docker push ktoni/multi-nginx
  - docker push ktoni/multi-server
  - docker push ktoni/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-ap-southeast-1-457821620636
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY